require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
Style/Documentation:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'config/initializers/simple_form.rb'
