default: &default
  adapter: postgresql
  encoding: unicode
  username: red_loyalty
  password: secret
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: red_loyalty_development

test:
  <<: *default
  database: red_loyalty_test

production:
  <<: *default
  database: red_loyalty_production
