default: &default
  adapter: postgresql
  encoding: unicode
  username: dot_loyalty
  password: secret
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: dot_loyalty_development

test:
  <<: *default
  database: dot_loyalty_test

production:
  <<: *default
  database: dot_loyalty_production
